[package]
name = "fluid_simulation"
version = "0.1.0"
authors = ["Damian Halatek <melman1996@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pixels = "0.3.0"
winit = "0.24"
winit_input_helper = "0.9"
